### ISSUE TITLE
[REFACTORING] `.searchInput` で明示的に `.color_white-a20` を使用する

### ISSUE THREAD

**Issue by matumoto1234** [Zli-UoA/ryouomoi-checker-frontend#75]
## 提案の詳細

- useSearchInput.css の現在
```css
.searchInput {
  justify-content: center;
  align-items: center;
  background: rgb(255 255 255 / 20%);
  border: 1px solid rgb(255 255 255 / 40%);
  box-sizing: border-box;
  border-radius: 88px;
  width: 100%;
  height: 32px;
}
```
- 理想
```css
.searchInput {
  justify-content: center;
  align-items: center;
  border: 1px solid rgb(255 255 255 / 40%);
  box-sizing: border-box;
  border-radius: 88px;
  width: 100%;
  height: 32px;
}
```

そもそも、`.color_white-a20` を color で適応じゃなくて background で適応させるようにする

## 動機

```jsx
<div className="color_white-a20">
  <Hoge />
</div>
```

この形に持っていきたい
