### ISSUE TITLE
[FEATURE] node_modules をキャッシュにのせる

### ISSUE THREAD

**Issue by matumoto1234** [Zli-UoA/ryouomoi-checker-frontend#96]
## 提案の詳細

以下をlinter.ymlに追記
```yml
      - name: Cache npm dir
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
```

## その他
